version: '3.8'

services:
  accounts_service:
    build: 
      context: ./accounts_service
      dockerfile: Dockerfile
    container_name: accounts_service
    ports:
      - "8000:8000"
    volumes:
      - ./accounts_service:/accounts_service
    environment:
      - FERNET_KEY="QM3CAYtgFqmIe1YGQV0OncGM3ArqTa11vzGpCv2xHdk="
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
